services:
  db:
    image: "postgres:17.4"
    restart: "on-failure:3"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "${VOLUME_DIR}/data/postgres:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:${DB_EXTERNAL_PORT}:5432"

  backend:
    build: "./backend"
    depends_on:
      - "db"
    restart: "on-failure:3"
    environment:
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${DB_NAME}"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      TZ: "America/Argentina/Buenos_Aires"
      JAVA_TOOL_OPTIONS: "-Duser.timezone=America/Argentina/Buenos_Aires"
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"

  frontend:
    build: "./frontend"
    depends_on:
      - "backend"
    restart: "on-failure:3"
    environment:
      BACKEND_EXTERNAL_URL: "${BACKEND_EXTERNAL_URL}"
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"

  adminer:
    image: "adminer:5.0.4"
    depends_on:
      - "db"
    restart: "on-failure:3"
    ports:
      - "${ADMINER_EXTERNAL_PORT}:8080"
